// Package assets embeds the app icon (generated by tools/genicon).
package assets

import "embed"

// Icon is the multi-size .ico used for the tray.
//
//go:embed icon.ico
var Icon []byte

// cli holds gdrive-ignore.com when the build script generated it.
//
//go:embed cli
var cli embed.FS

// CLILauncher returns the console launcher (gdrive-ignore.com), or nil when
// this build does not include it (e.g. a plain `go build`).
func CLILauncher() []byte {
	b, err := cli.ReadFile("cli/gdrive-ignore.com")
	if err != nil {
		return nil
	}
	return b
}
